version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

workflows:
  build-pack-deploy:
    jobs:
      - build