version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm i --prefix src/

jobs:
  build:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - install_dependencies

      - run:
          name: Build and Compile
          command: |
            npm build

  pack:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_dependencies

      - run:
          name: Compile
          command: |
            npm i npm@latest

      - store_artifacts:
          path: simpletodoapp-1.0.0.tgz

  e2e-test:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    steps:
    - checkout
    - install_dependencies

    - run:
        name: Start and Run MongoDB
        command: |
          npm run start --prefix src/
          
    - run:
        name: CHMOD into Scripts folder
        command: |
          chmod +x scripts/e2e-ci.sh
          ./scripts/e2e-ci.sh

    - run:
        name: E2E Test
        command: |
          npm run test-e2e --prefix src/

workflows:
  end-to-end-ops:
    jobs:
      - build
      - pack:
          requires:
            - build

      - e2e-test:
          requires:
            - build
        