version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm ci --prefix src/

jobs:
  build:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - install_dependencies

      - run:
          name: Build and Compile
          command: |
            npm build

  pack:
    docker:
      - image: circleci/node:lts

    steps:
      - run:
          name: Compile
          command: |
            npm i -g npm@latest

workflows:
  build-pack-deploy:
    jobs:
      - build