version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm i --prefix src/

jobs:
  build:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - install_dependencies

      - run:
          name: Build and Compile
          command: |
            npm build

  pack:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_dependencies

      - run:
          name: Compile
          command: |
            npm i npm@latest

      - store_artifacts:
          path: simpletodoapp-1.0.0.tgz

  jest:
    docker:
      - image: circleci/node:lts

    environment:
      JEST_JUNIT_OUTPUT_DIR: test/unit

    steps:
      - checkout
      - install_dependencies

      - run:
          name: Unit Test with Jest JUnit
          command: |
            npm run test-unit --prefix src/

      - store_test_results:
          path: test/unit

workflows:
  buildNpack2jest:
    jobs:
      - build
      - pack:
          requires:
            - build

      - jest:
          requires:
            - build
            - pack
        