version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm ci --prefix src/

jobs:
  build:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - install_dependencies

      - run:
          name: Build and Compile
          command: |
            npm build

  pack:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_dependencies

      - run:
          name: Start Test Service
          command: |
            npm run start

      - run:
          name: Compile
          command: |
            npm i npm@latest

      - store_artifacts:
          path: simpletodoapp-1.0.0.tgz

  integrate:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0

    environment:
      JEST_JUNIT_OUTPUT_DIR: test/unit

    steps:
      - run:
          name: Start Services (MongoDB; etc.)
          command: |
            npm run start --prefix src/

      - run:
          name: Integration Test
          command: |
            npm run test-integration --prefix src/

      - store_test_results:
          path: test/integration

workflows:
  integration:
    jobs:
      - build
      - pack:
          requires:
            - build

      - integrate:
          requires:
            - build
        